version: "3.9"
services:
  grafana:
    build:
      context: ./images/grafana
    volumes:
      - "grafana:/var/lib/grafana"
    networks:
      main:
  loki:
    build: ./images/loki
    volumes:
      - "loki:/var/lib/loki"
    command: ["-config.file=/etc/loki/config.yaml"]
    networks:
      main:
  prometheus:
    build: ./images/prometheus
    volumes:
      - "prometheus:/prometheus"
    networks:
      main:
  promtail:
    build: images/promtail
    volumes:
      - "/var/log/journal/:/var/log/journal/"
      - "/run/log/journal/:/run/log/journal/"
      - "/etc/machine-id:/etc/machine-id"
      - "promtail:/var/lib/promtail"
    command: ["-config.file=/etc/promtail/config.yml"]
    networks:
      main:
  geth:
    build: images/geth
    volumes:
      - "geth:/home/somebody/.ethereum"
    ports:
      - "30303:30303/tcp"
      - "30303:30303/udp"
    networks:
      main:
  lighthouse:
    build: images/lighthouse
    volumes:
      - "lighthouse:/home/somebody/.lighthouse"
      - "./validator-pubkeys.txt:/home/somebody/validator-pubkeys.txt"
    ports:
      - "9000:9000/tcp"
      - "9000:9000/udp"
    environment:
      ETH1_HOST: geth
    networks:
      main:
  prysm:
    build: images/prysm
    volumes:
      - "prysm:/home/somebody/.eth2"
    environment:
      ETH1_HOST: geth
    ports:
      - "12000:12000/udp"
      - "13000:13000/tcp"
    networks:
      main:
  ssh:
    build: images/ssh
    expose:
      - "5064"
      - "8081"
    ports:
      - "2222:22"
    volumes:
      - "supervisor_backups:/home/somebody/supervisor-backups"
      - "ssh_host_keys:/etc/ssh/host-keys"
      - "./authorized_keys:/home/somebody/.ssh/authorized_keys"
    networks:
      main:
        aliases:
          - validator-proxy
networks:
  main:
    driver: bridge
volumes:
  grafana:
  loki:
  promtail:
  geth:
  prysm:
  prometheus:
  lighthouse:
  ssh_host_keys:
  supervisor_backups:
