version: "3.9"
services:
  node:
    build:
      context: test/images/ssh
    ports:
      - "2222:22"
    links:
      - lighthouse
  lighthouse:
    build: test/images/lighthouse
    ports:
      - "5052:5052"
