services:
  node:
    build:
      context: test/images/ssh
    ports:
      - "2222:22"
      - "2223:22"
    networks:
      internal:
  lighthouse:
    build: test/images/lighthouse
    ports:
      - "5052:5052"
    networks:
      internal:
        aliases:
          - host.docker.internal
networks:
  internal:
