version: 1
disable_existing_loggers: False
handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
root:
  level: DEBUG
  handlers: [console]
loggers:
  asyncio:
    level: DEBUG
